In [1]:
print("test")

test


In [17]:
import numpy as np
# arange returns evenly spaced values within a given interval
a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [33]:
#reshape gives a new shape to an array without changing its data.
a = np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [34]:
a = np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [35]:
a.shape
#shows the dimensions of the array

(3, 5)

In [36]:
a.ndim

2

In [37]:
#n object describing the type of the elements in the array.
a.dtype.name

'int32'

In [39]:
#the size in bytes of each element of the array. 
a.itemsize

4

In [40]:
#the total number of elements of the array
a.size

15

In [41]:
#an object describing the type of the elements in the array.
type(a)

numpy.ndarray

In [49]:
#the buffer containing the actual elements of the array.
b = np.array([1,2,3])
b

array([1, 2, 3])

In [50]:
type(b)

numpy.ndarray

In [51]:
b.dtype

dtype('int32')

In [57]:
c = np.array([1.2,2,2.4])
c

array([1.2, 2. , 2.4])

In [53]:
c.dtype

dtype('float64')

In [58]:
d = np.array([(1,2,3),(4,5,6)])
d

array([[1, 2, 3],
       [4, 5, 6]])

In [60]:
d.dtype

dtype('int32')

In [62]:
e = np.array(([(1,2,3),(4,5,6)]), dtype = complex)
e

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j]])

In [74]:
#The function zeros creates an array full of zeros
f = np.zeros( (3,4) )
f
#np.zeros( (3,4) )

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [70]:
#the function ones creates an array full of ones
f = np.ones( (2,3,4), dtype=np.int16 )
f

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [76]:
#the function empty creates an array whose initial content is random and 
#depends on the state of the memory. By default, the dtype of the created array is float64.
np.empty( (2,3) )   

array([[0., 0., 0.],
       [0., 0., 0.]])

In [77]:
#To create sequences of numbers, NumPy provides a function analogous to range that returns arrays instead of lists.
np.arange( 10, 30, 5 )

array([10, 15, 20, 25])

In [78]:
np.arange( 0, 2, 0.3 )   

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [79]:
from numpy import pi
np.linspace( 0, 2, 9 )                 # 9 numbers from 0 to 2

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [81]:
x = np.linspace( 0, 2*pi, 100 )        # useful to evaluate function at lots of points
x

array([0.        , 0.06346652, 0.12693304, 0.19039955, 0.25386607,
       0.31733259, 0.38079911, 0.44426563, 0.50773215, 0.57119866,
       0.63466518, 0.6981317 , 0.76159822, 0.82506474, 0.88853126,
       0.95199777, 1.01546429, 1.07893081, 1.14239733, 1.20586385,
       1.26933037, 1.33279688, 1.3962634 , 1.45972992, 1.52319644,
       1.58666296, 1.65012947, 1.71359599, 1.77706251, 1.84052903,
       1.90399555, 1.96746207, 2.03092858, 2.0943951 , 2.15786162,
       2.22132814, 2.28479466, 2.34826118, 2.41172769, 2.47519421,
       2.53866073, 2.60212725, 2.66559377, 2.72906028, 2.7925268 ,
       2.85599332, 2.91945984, 2.98292636, 3.04639288, 3.10985939,
       3.17332591, 3.23679243, 3.30025895, 3.36372547, 3.42719199,
       3.4906585 , 3.55412502, 3.61759154, 3.68105806, 3.74452458,
       3.8079911 , 3.87145761, 3.93492413, 3.99839065, 4.06185717,
       4.12532369, 4.1887902 , 4.25225672, 4.31572324, 4.37918976,
       4.44265628, 4.5061228 , 4.56958931, 4.63305583, 4.69652

In [83]:
f = np.sin(x)
f

array([ 0.00000000e+00,  6.34239197e-02,  1.26592454e-01,  1.89251244e-01,
        2.51147987e-01,  3.12033446e-01,  3.71662456e-01,  4.29794912e-01,
        4.86196736e-01,  5.40640817e-01,  5.92907929e-01,  6.42787610e-01,
        6.90079011e-01,  7.34591709e-01,  7.76146464e-01,  8.14575952e-01,
        8.49725430e-01,  8.81453363e-01,  9.09631995e-01,  9.34147860e-01,
        9.54902241e-01,  9.71811568e-01,  9.84807753e-01,  9.93838464e-01,
        9.98867339e-01,  9.99874128e-01,  9.96854776e-01,  9.89821442e-01,
        9.78802446e-01,  9.63842159e-01,  9.45000819e-01,  9.22354294e-01,
        8.95993774e-01,  8.66025404e-01,  8.32569855e-01,  7.95761841e-01,
        7.55749574e-01,  7.12694171e-01,  6.66769001e-01,  6.18158986e-01,
        5.67059864e-01,  5.13677392e-01,  4.58226522e-01,  4.00930535e-01,
        3.42020143e-01,  2.81732557e-01,  2.20310533e-01,  1.58001396e-01,
        9.50560433e-02,  3.17279335e-02, -3.17279335e-02, -9.50560433e-02,
       -1.58001396e-01, -

In [94]:
#One-dimensional arrays are then printed as rows, bidimensionals as matrices and tridimensionals as lists of matrices.
a = np.arange(6)                         # 1d array
print("1d array")
print(a)
print("")
b = np.arange(12).reshape(4,3)           # 2d array
print("2d array")
print(b)
print("")
c = np.arange(24).reshape(2,3,4)         # 3d array
print("3d array")
print(c)

1d array
[0 1 2 3 4 5]

2d array
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

3d array
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [96]:
#If an array is too large to be printed, NumPy automatically skips the central part of the array and only prints the corners:
print(np.arange(10000))

[   0    1    2 ... 9997 9998 9999]


In [97]:
print(np.arange(10000).reshape(100,100))

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


In [100]:
a = np.array( [20,30,40,50] )
b = np.arange( 4 )
print(b)
c = a-b
print(c)

[0 1 2 3]
[20 29 38 47]


In [104]:
b**2

array([0, 1, 4, 9], dtype=int32)

In [105]:
10*np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [107]:
a<35

array([ True,  True, False, False])